services:

  django:
    environment:
      DJANGO_SETTINGS_MODULE: src.main.settings
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  nginx:
    image: wodby/nginx:1.28-5.43.0
    depends_on:
      - django
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_VHOST_PRESET: django
      NGINX_BACKEND_HOST: django
    volumes:
      - ./src/:/usr/src/app/src:cached
